# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apollo2_api_client
from apollo2_api_client.models.incas_actor import IncasActor  # noqa: E501
from apollo2_api_client.rest import ApiException


class TestIncasActor(unittest.TestCase):
    """IncasActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncasActor(self):
        """Test IncasActor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apollo2_api_client.models.incas_actor.IncasActor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
