# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import apollo2_api_client
from apollo2_api_client.models.incas_links import IncasLinks  # noqa: E501
from apollo2_api_client.rest import ApiException

class TestIncasLinks(unittest.TestCase):
    """IncasLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IncasLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IncasLinks`
        """
        model = apollo2_api_client.models.incas_links.IncasLinks()  # noqa: E501
        if include_optional :
            return IncasLinks(
                messages = '', 
                var_self = ''
            )
        else :
            return IncasLinks(
        )
        """

    def testIncasLinks(self):
        """Test IncasLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
