# coding: utf-8

"""
    Mips UIUC Datatypes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mips_api_client
from mips_api_client.api.item_api import ItemApi  # noqa: E501
from mips_api_client.rest import ApiException


class TestItemApi(unittest.TestCase):
    """ItemApi unit test stubs"""

    def setUp(self):
        self.api = ItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_item_attach_media_post(self):
        """Test case for item_attach_media_post

        Item Attach Media Post  # noqa: E501
        """
        pass

    def test_item_batch_get(self):
        """Test case for item_batch_get

        Item Batch Get  # noqa: E501
        """
        pass

    def test_item_count_get(self):
        """Test case for item_count_get

        Item Count Get  # noqa: E501
        """
        pass

    def test_item_detach_media_post(self):
        """Test case for item_detach_media_post

        Item Detach Media Post  # noqa: E501
        """
        pass

    def test_item_enrichments_batch_delete(self):
        """Test case for item_enrichments_batch_delete

        Item Enrichments Batch Delete  # noqa: E501
        """
        pass

    def test_item_enrichments_batch_get(self):
        """Test case for item_enrichments_batch_get

        Item Enrichments Batch Get  # noqa: E501
        """
        pass

    def test_item_enrichments_batch_post(self):
        """Test case for item_enrichments_batch_post

        Item Enrichments Batch Post  # noqa: E501
        """
        pass

    def test_item_get(self):
        """Test case for item_get

        Item Get  # noqa: E501
        """
        pass

    def test_item_id_delete(self):
        """Test case for item_id_delete

        Item Id Delete  # noqa: E501
        """
        pass

    def test_item_id_enrichments_delete(self):
        """Test case for item_id_enrichments_delete

        Item Id Enrichments Delete  # noqa: E501
        """
        pass

    def test_item_id_enrichments_get(self):
        """Test case for item_id_enrichments_get

        Item Id Enrichments Get  # noqa: E501
        """
        pass

    def test_item_id_enrichments_post(self):
        """Test case for item_id_enrichments_post

        Item Id Enrichments Post  # noqa: E501
        """
        pass

    def test_item_id_forward_batch_translate(self):
        """Test case for item_id_forward_batch_translate

        Item Id Forward Batch Translate  # noqa: E501
        """
        pass

    def test_item_id_forward_translate(self):
        """Test case for item_id_forward_translate

        Item Id Forward Translate  # noqa: E501
        """
        pass

    def test_item_id_get(self):
        """Test case for item_id_get

        Item Id Get  # noqa: E501
        """
        pass

    def test_item_id_reverse_batch_translate(self):
        """Test case for item_id_reverse_batch_translate

        Item Id Reverse Batch Translate  # noqa: E501
        """
        pass

    def test_item_id_reverse_translate(self):
        """Test case for item_id_reverse_translate

        Item Id Reverse Translate  # noqa: E501
        """
        pass

    def test_item_max_id_get(self):
        """Test case for item_max_id_get

        Item Max Id Get  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
