# coding: utf-8

"""
    Mips UIUC Datatypes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mips_api_client
from mips_api_client.models.twitter_public_metrics import TwitterPublicMetrics  # noqa: E501
from mips_api_client.rest import ApiException


class TestTwitterPublicMetrics(unittest.TestCase):
    """TwitterPublicMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwitterPublicMetrics(self):
        """Test TwitterPublicMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mips_api_client.models.twitter_public_metrics.TwitterPublicMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
