# coding: utf-8

"""
    Mips UIUC Datatypes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mips_api_client
from mips_api_client.api.admin_api import AdminApi  # noqa: E501
from mips_api_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_data_post(self):
        """Test case for admin_data_post

        Admin Data Post  # noqa: E501
        """
        pass

    def test_admin_flush(self):
        """Test case for admin_flush

        Admin Flush  # noqa: E501
        """
        pass

    def test_status_get(self):
        """Test case for status_get

        Status Get  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
