# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import apollo2_api_client
from apollo2_api_client.models.twitter_entities import TwitterEntities  # noqa: E501
from apollo2_api_client.rest import ApiException

class TestTwitterEntities(unittest.TestCase):
    """TwitterEntities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TwitterEntities
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwitterEntities`
        """
        model = apollo2_api_client.models.twitter_entities.TwitterEntities()  # noqa: E501
        if include_optional :
            return TwitterEntities(
                annotations = [
                    apollo2_api_client.models.twitter_annotation.TwitterAnnotation(
                        end = 56, 
                        normalized_text = '', 
                        probability = 1.337, 
                        start = 56, 
                        type = '', )
                    ], 
                hashtags = [
                    apollo2_api_client.models.twitter_hashtag.TwitterHashtag(
                        end = 56, 
                        start = 56, 
                        tag = '', )
                    ], 
                mentions = [
                    apollo2_api_client.models.twitter_mention.TwitterMention(
                        end = 56, 
                        id = '', 
                        start = 56, 
                        username = '', )
                    ]
            )
        else :
            return TwitterEntities(
        )
        """

    def testTwitterEntities(self):
        """Test TwitterEntities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
