# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import apollo2_api_client
from apollo2_api_client.models.enrichment_type import EnrichmentType  # noqa: E501
from apollo2_api_client.rest import ApiException

class TestEnrichmentType(unittest.TestCase):
    """EnrichmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnrichmentType(self):
        """Test EnrichmentType"""
        # inst = EnrichmentType()

if __name__ == '__main__':
    unittest.main()
