# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import apollo2_api_client
from apollo2_api_client.model.enrichment import Enrichment
from apollo2_api_client import configuration


class TestEnrichment(unittest.TestCase):
    """Enrichment unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
