# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from apollo2_api_client import schemas  # noqa: F401


class EntityType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "ENTITY_UNSPECIFIED": "ENTITY_UNSPECIFIED",
            "Person": "PERSON",
            "Media": "MEDIA",
            "Organization": "ORGANIZATION",
            "Government": "GOVERNMENT",
        }
    
    @schemas.classproperty
    def ENTITY_UNSPECIFIED(cls):
        return cls("ENTITY_UNSPECIFIED")
    
    @schemas.classproperty
    def PERSON(cls):
        return cls("Person")
    
    @schemas.classproperty
    def MEDIA(cls):
        return cls("Media")
    
    @schemas.classproperty
    def ORGANIZATION(cls):
        return cls("Organization")
    
    @schemas.classproperty
    def GOVERNMENT(cls):
        return cls("Government")
