# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401

from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from apollo2_api_client.models.claim import Claim
from apollo2_api_client.models.segment import Segment
from apollo2_api_client.models.visual_topic import VisualTopic
from typing import Any, List
from pydantic import StrictStr, Field

CLUSTER_ANY_OF_SCHEMAS = ["Claim", "Segment", "VisualTopic"]

class Cluster(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    # data type: Segment
    __anyof_schema_1: Optional[Segment] = None
    # data type: Claim
    __anyof_schema_2: Optional[Claim] = None
    # data type: VisualTopic
    __anyof_schema_3: Optional[VisualTopic] = None
    actual_instance: Any
    any_of_schemas: List[str] = Field(CLUSTER_ANY_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    @validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        error_messages = []
        # validate data type: Segment
        if type(v) is not Segment:
            error_messages.append(f"Error! Input type `{type(v)}` is not `Segment`")
        else:
            return v

        # validate data type: Claim
        if type(v) is not Claim:
            error_messages.append(f"Error! Input type `{type(v)}` is not `Claim`")
        else:
            return v

        # validate data type: VisualTopic
        if type(v) is not VisualTopic:
            error_messages.append(f"Error! Input type `{type(v)}` is not `VisualTopic`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Cluster with anyOf schemas: Claim, Segment, VisualTopic. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_json(cls, json_str: str) -> Cluster:
        """Returns the object represented by the json string"""
        instance = cls()
        error_messages = []
        # __anyof_schema_1: Optional[Segment] = None
        try:
            instance.actual_instance = Segment.from_json(json_str)
            return instance
        except ValidationError as e:
             error_messages.append(str(e))
        # __anyof_schema_2: Optional[Claim] = None
        try:
            instance.actual_instance = Claim.from_json(json_str)
            return instance
        except ValidationError as e:
             error_messages.append(str(e))
        # __anyof_schema_3: Optional[VisualTopic] = None
        try:
            instance.actual_instance = VisualTopic.from_json(json_str)
            return instance
        except ValidationError as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Cluster with anyOf schemas: Claim, Segment, VisualTopic. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is not None:
            return self.actual_instance.to_json()
        else:
            return "null"

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is not None:
            return self.actual_instance.to_dict()
        else:
            return dict()

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())

