# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr, conlist
from apollo2_api_client.models.edge import Edge
from apollo2_api_client.models.graph_type import GraphType

class Graph(BaseModel):
    """
    Graph
    """
    id: Optional[StrictInt] = None
    name: StrictStr = ...
    provider: StrictStr = ...
    tag: StrictStr = ...
    version: StrictStr = ...
    type: GraphType = ...
    edges: Optional[conlist(Edge)] = None
    data: Optional[Dict[str, Any]] = None
    __properties = ["id", "name", "provider", "tag", "version", "type", "edges", "data"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Graph:
        """Create an instance of Graph from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item in self.edges:
                if _item:
                    _items.append(_item.to_dict())
            _dict['edges'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Graph:
        """Create an instance of Graph from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return Graph.parse_obj(obj)

        _obj = Graph.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "provider": obj.get("provider"),
            "tag": obj.get("tag"),
            "version": obj.get("version"),
            "type": obj.get("type"),
            "edges": [Edge.from_dict(_item) for _item in obj.get("edges")] if obj.get("edges") is not None else None,
            "data": obj.get("data")
        })
        return _obj

