# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from apollo2_api_client.models.incas_actor import IncasActor
from apollo2_api_client.models.reddit_user_data import RedditUserData
from apollo2_api_client.models.twitter_user_data import TwitterUserData
from typing import Any, List
from pydantic import StrictStr, Field

SOURCE_DATA_ANY_OF_SCHEMAS = ["IncasActor", "RedditUserData", "TwitterUserData"]

class SourceData(BaseModel):
    """
    SourceData
    """

    # data type: TwitterUserData
    anyof_schema_1_validator: Optional[TwitterUserData] = None
    # data type: RedditUserData
    anyof_schema_2_validator: Optional[RedditUserData] = None
    # data type: IncasActor
    anyof_schema_3_validator: Optional[IncasActor] = None
    actual_instance: Any
    any_of_schemas: List[str] = Field(SOURCE_DATA_ANY_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    @validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = cls()
        error_messages = []
        # validate data type: TwitterUserData
        if type(v) is not TwitterUserData:
            error_messages.append(f"Error! Input type `{type(v)}` is not `TwitterUserData`")
        else:
            return v

        # validate data type: RedditUserData
        if type(v) is not RedditUserData:
            error_messages.append(f"Error! Input type `{type(v)}` is not `RedditUserData`")
        else:
            return v

        # validate data type: IncasActor
        if type(v) is not IncasActor:
            error_messages.append(f"Error! Input type `{type(v)}` is not `IncasActor`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SourceData with anyOf schemas: IncasActor, RedditUserData, TwitterUserData. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> SourceData:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> SourceData:
        """Returns the object represented by the json string"""
        instance = cls()
        error_messages = []
        # anyof_schema_1_validator: Optional[TwitterUserData] = None
        try:
            instance.actual_instance = TwitterUserData.from_json(json_str)
            return instance
        except ValidationError as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[RedditUserData] = None
        try:
            instance.actual_instance = RedditUserData.from_json(json_str)
            return instance
        except ValidationError as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[IncasActor] = None
        try:
            instance.actual_instance = IncasActor.from_json(json_str)
            return instance
        except ValidationError as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SourceData with anyOf schemas: IncasActor, RedditUserData, TwitterUserData. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is not None:
            return self.actual_instance.to_json()
        else:
            return "null"

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is not None:
            return self.actual_instance.to_dict()
        else:
            return dict()

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())

