# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from apollo2_api_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    PING = "/ping"
    DATA = "/data"
    STATUS = "/status"
    DBFLUSH = "/dbflush"
    ITEM_COUNT = "/item/count"
    ITEM_MAX_ID = "/item/max_id"
    ITEM = "/item"
    ITEM_GET = "/item/get"
    ITEM_ID_FORWARD = "/item/id/forward"
    ITEM_ID_FORWARD_ID = "/item/id/forward/{id}"
    ITEM_ID_REVERSE = "/item/id/reverse"
    ITEM_ID_REVERSE_ID = "/item/id/reverse/{id}"
    ITEM_ID = "/item/{id}"
    ITEM_ID_ENRICHMENTS = "/item/{id}/enrichments"
    ITEM_ENRICHMENTS_GET = "/item/enrichments/get"
    ITEM_ENRICHMENTS_SUBMIT = "/item/enrichments/submit"
    ITEM_ENRICHMENTS_DELETE = "/item/enrichments/delete"
    ITEM_ATTACH_MEDIA = "/item/attach_media"
    ITEM_DETACH_MEDIA = "/item/detach_media"
    ITEM_IDENTIFER_POST = "/item/identifer/post"
    ITEM_IDENTIFER_DELETE = "/item/identifer/delete"
    ITEM_ID_IDENTIFER = "/item/{id}/identifer"
    SOURCE_COUNT = "/source/count"
    SOURCE_MAX_ID = "/source/max_id"
    SOURCE = "/source"
    SOURCE_GET = "/source/get"
    SOURCE_ID_FORWARD = "/source/id/forward"
    SOURCE_ID_FORWARD_ID = "/source/id/forward/{id}"
    SOURCE_ID_REVERSE = "/source/id/reverse"
    SOURCE_ID_REVERSE_ID = "/source/id/reverse/{id}"
    SOURCE_ID = "/source/{id}"
    SOURCE_ID_ENRICHMENTS = "/source/{id}/enrichments"
    SOURCE_ENRICHMENTS_GET = "/source/enrichments/get"
    SOURCE_ENRICHMENTS_SUBMIT = "/source/enrichments/submit"
    SOURCE_ENRICHMENTS_DELETE = "/source/enrichments/delete"
    SOURCE_IDENTIFER_POST = "/source/identifer/post"
    SOURCE_IDENTIFER_DELETE = "/source/identifer/delete"
    SOURCE_ID_IDENTIFER = "/source/{id}/identifer"
    ENRICHMENTS_META = "/enrichments/meta"
    CLUSTER = "/cluster"
    CLUSTER_ID = "/cluster/{id}"
    CLUSTER_ID_MEMBERS = "/cluster/{id}/members"
    CLUSTER_ID_DELETE_MEMBERS = "/cluster/{id}/delete_members"
    CLUSTER_ID_ENRICHMENTS = "/cluster/{id}/enrichments"
    CLUSTER_ENRICHMENTS_GET = "/cluster/enrichments/get"
    CLUSTER_ENRICHMENTS_SUBMIT = "/cluster/enrichments/submit"
    CLUSTER_ENRICHMENTS_DELETE = "/cluster/enrichments/delete"
    CLUSTER_IDENTIFER_POST = "/cluster/identifer/post"
    CLUSTER_IDENTIFER_DELETE = "/cluster/identifer/delete"
    CLUSTER_ID_IDENTIFER = "/cluster/{id}/identifer"
    GRAPH = "/graph"
    GRAPH_ID = "/graph/{id}"
    GRAPH_ID_EDGES = "/graph/{id}/edges"
    GRAPH_ID_EDIT_EDGES = "/graph/{id}/edit_edges"
    GRAPH_ID_DELETE_EDGES = "/graph/{id}/delete_edges"
    GRAPH_EDGE_IDENTIFER_POST = "/graph/edge/identifer/post"
    GRAPH_EDGE_IDENTIFER_DELETE = "/graph/edge/identifer/delete"
    GRAPH_ID_EDGE_IDENTIFER_ALL = "/graph/{id}/edge/identifer/all"
    GRAPH_ID_EDGE_IDENTIFER = "/graph/{id}/edge/identifer"
    MEDIA_ITEM_COUNT = "/media_item/count"
    MEDIA_ITEM_MAX_ID = "/media_item/max_id"
    MEDIA_ITEM = "/media_item"
    MEDIA_ITEM_GET = "/media_item/get"
    MEDIA_ITEM_ID = "/media_item/{id}"
    MEDIA_ITEM_IDENTIFER_POST = "/media_item/identifer/post"
    MEDIA_ITEM_IDENTIFER_DELETE = "/media_item/identifer/delete"
    MEDIA_ITEM_ID_IDENTIFER = "/media_item/{id}/identifer"
    IDENTIFIER_LIST = "/identifier/list"
    IDENTIFER_DELETE = "/identifer/delete"
