# coding: utf-8

# flake8: noqa

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from apollo2_api_client.api_client import ApiClient

# import Configuration
from apollo2_api_client.configuration import Configuration

# import exceptions
from apollo2_api_client.exceptions import OpenApiException
from apollo2_api_client.exceptions import ApiAttributeError
from apollo2_api_client.exceptions import ApiTypeError
from apollo2_api_client.exceptions import ApiValueError
from apollo2_api_client.exceptions import ApiKeyError
from apollo2_api_client.exceptions import ApiException
