# coding: utf-8

"""
    Apollo2 API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from apollo2_api_client.paths.graph_edge_identifer_delete.delete import EdgeIdentiferDelete
from apollo2_api_client.paths.graph_edge_identifer_post.post import EdgeIdentiferPost
from apollo2_api_client.paths.graph.get import GraphGet
from apollo2_api_client.paths.graph_id.delete import GraphIdDelete
from apollo2_api_client.paths.graph_id_delete_edges.post import GraphIdDeleteEdgesPost
from apollo2_api_client.paths.graph_id_edge_identifer_all.get import GraphIdEdgeIdentiferAllGet
from apollo2_api_client.paths.graph_id_edge_identifer.get import GraphIdEdgeIdentifierGet
from apollo2_api_client.paths.graph_id_edges.get import GraphIdEdgesGet
from apollo2_api_client.paths.graph_id_edit_edges.post import GraphIdEditEdgesPost
from apollo2_api_client.paths.graph_id.get import GraphIdGet
from apollo2_api_client.paths.graph.post import GraphPost


class GraphApi(
    EdgeIdentiferDelete,
    EdgeIdentiferPost,
    GraphGet,
    GraphIdDelete,
    GraphIdDeleteEdgesPost,
    GraphIdEdgeIdentiferAllGet,
    GraphIdEdgeIdentifierGet,
    GraphIdEdgesGet,
    GraphIdEditEdgesPost,
    GraphIdGet,
    GraphPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
